### PR TITLE
Doc fixes for default constructor name & SharedAnnotation

### PR DESCRIPTION
**Pull request by jvasileff**

### CODE REVIEW

**Comment by gavinking** [comment]
Thanks.

**Comment by lucaswerkmeister** [comment]
> ```ceylon
>     // Does the process declaration have the Shared annotation?
>     value isShared = optionalAnnotation(`SharedAnnotation`, `value process`) exists;
> ```

According to this code, `process` is *not* shared, neither as `` `class process` `` nor as `` `value process` ``. Is that bug already tracked somewhere?

**Comment by jvasileff** [comment]
Ha, leave it to @lucaswerkmeister to actually *run* the sample code!

I wonder if this is https://github.com/ceylon/ceylon.language/issues/408

**Comment by lucaswerkmeister** [comment]
> Ha, leave it to @lucaswerkmeister to actually run the sample code!

I actually noticed this outdated doc a couple weeks ago, ran it, noticed the bug, tried to investigate it, didn’t get anywhere, forgot about it without fixing the documentation. So leave it to @jvasileff to actually *do* something about bugs he finds :D

> I wonder if this is #408

Hm, that might be it. `ceylon.json::nil` works.

**Pull request merged**
