### PR TITLE
List.permutations without repeats

### PR DESCRIPTION
**Pull request by gdejohn**
@gavinking, sorry this took so long. I got it working right away with a very neat constant time algorithm for generating successive distinct permutations, but I spent several days banging my head against the wall trying to make the individual permutations lazy to actually take advantage of the time complexity.

The problem is that each permutation is a view of the same underlying data structure, so when changing that data structure in place to get the next permutation I have to mark the previous view as dirty and throw an exception if the caller ever tries to iterate it again.

It works, and you can just eagerly copy a permutation into a collection if you want to use it later, but I figured that was actually asking too much. Just getting the string representation of the whole stream blows up, since I guess there's code somewhere in `Iterable.string` that assumes a stable iteration order and holds onto the first element, evaluating it after having advanced the iterator. I can address that and similar situations case by case, but I can't plug all the holes.

So I switched to another algorithm that enumerates distinct permutations in lexicographic order (according to the order of the first occurrence of each distinct element of the list, treating nulls as equal to each other and distinct from objects). It's not constant time, but that doesn't really matter because each permutation is copied to a sequence.

### CODE REVIEW

**Comment by gavinking** [comment]
@gdejohn Thanks!

So, here's my question: how does this algorithm compare to calling `list.permutations.distinct`?

An interesting test case is to time `"helloworld"`.permutations.distinct.size`.

**Comment by gdejohn** [comment]
I think the running time of your implementation is greater by a factor of the product of the multiplicities of each distinct element in the original list. So `list.permutations.distinct` would be extremely inefficient if there were lots of repetitions.

**Comment by gavinking** [comment]
@gdejohn what is the status of this now? Do you think I should merge it?

**Comment by gdejohn** [comment]
Well, it works fine. The one salient thing Scala does differently is to keep track of the elements and the indexes in different arrays, swapping them separately instead of what I did packing them together with `Iterable.indexed` and splitting out the elements when it comes time to materialize a permutation. I haven't addressed that yet because I'm blocked by schoolwork. Do you want me to take some more time to try that? Or does this need to be merged really soon?

You don't want this to be `default`, right?

**Comment by gavinking** [comment]
Thank you @gdejohn!

**Comment by gavinking** [comment]
@gdejohn it doesn't look like the lexicographic ordering is preserved when there are repeated elements.

    print("ABA".permutations.map(String));

Prints:

    { BAA, ABA, AAB }

**Comment by gavinking** [comment]
@gdejohn in @5ecadb85c961a67ccaeae59016b5410a3e64ab20 I have made some changes to the implementation of the second half of your algorithm.

Previously you were using streams of tuples to do some stuff that is essentially just array element swapping. I found this logic extremely difficult to understand, and it's also not especially efficient (though it probably doesn't dominate performance in this case).

My reimplementation uses boring-old array indices and the new `swap()` method of array. It's shorter and easier to understand, I think.

I have barely touched the first half of your algorithm, which is a rather elegant use of Ceylon streams. (One of the best examples I've seen.) As much as I like it, the two calls to `indexed` quite possibly dominate performance of the whole algorithm with all that `Entry` instantiation. So I would definitely like to see you do the thing you suggested above about reworking it to use two arrays instead of the array of `Entry`s.

Thoughts?

**Pull request merged**
