### PR TITLE
Curry loop()

### PR DESCRIPTION
**Pull request by gdejohn**
As with `Iterable.fold()` (#540).

### CODE REVIEW

**Comment by gavinking** [comment]
Eeeek, I agree that this is much better. It's a breaking change, though....

WDYT, folks, is it OK to make this change?

**Comment by quintesse** [comment]
Seems to me we don't have much choice, leaving it to be different from the rest is just ugly. Just put it in the bag of other breaking changes for 1.2

**Comment by gavinking** [comment]
Well, what other breaking changes have we made? Off the top of my head I can't recall any. We have been trying _very_ hard to avoid them. Even at the binary level.

**Comment by gavinking** [comment]
I have merged it. I doubt that there is very much code depending on `loop()`, and surely people who are using it are going to prefer it this way. Better to break things sooner than later.

**Comment by gavinking** [comment]
Thanks @gdejohn.

**Pull request merged**
